src/pygeometadata/mcf.py
tests/test_mcf.py

I built a basic MCF for all the `.shp, .gpkg, and .tif` in our invest sampledata repo and a few other workspaces and a couple small bugs were revealed:
1. Correctly handle pygeoprocessing's `ValueError` on non-gdal datasets.
2. create valid MCF for vectors that have no attributes and rasters that have no bands

A couple quick fixes

---

src/geometamaker/geometamaker.py
tests/data/template.yml
tests/test_geometamaker.py

This PR adds support for `.csv` files, by treating them like other vector datasets that GDAL supports.
A couple other things here:
* Debugged some issues with overwriting existing MCF data when a `MetadataControl` is initialized. The goal is to preserve any metadata that might already exist, except for properties that are intrinsic to the dataset (i.e. CRS, bounding box, field names & datatypes).
* changed some function keyword arg names to match the names of the MCF properties they represent. This makes it easy to use a pattern like `mc_a.set_license(**mc_b.get_license())`

Handle CSV datasets & better handle updates to existing MCF

---

src/geometamaker/geometamaker.py
tests/test_geometamaker.py

Fixes #16 
This PR adds tests that use a few common GDAL vector formats. And it fixes the issue where `open_options` that we want to use for CSVs were also being applied to other formats. GDAL would ignore them but issue a warning.

pass GDAL open_options that are appropriate for the vector format

---

README.md
src/geometamaker/geometamaker.py
tests/data/template.yml
tests/test_geometamaker.py

Fixes #17 
`url` and `doi` appear in the `identification` section of the core MCF spec, with `url` being a required property (it can be blank). `citation` does not appear in the MCF spec, but I added it here, also in the `identification` section.

Add url, citation, doi metadata properties

---

.github/workflows/test.yml
pyproject.toml
src/geometamaker/geometamaker.py
tests/test_geometamaker.py

Fixes #31 
I also removed the test runs for Python 3.8 and 3.9 because we decided during #24 that it's okay to use `dataclasses` features that were introduced in 3.10.

improve an error message.

---

pyproject.toml
src/geometamaker/geometamaker.py
src/geometamaker/models.py
tests/test_geometamaker.py

A few metadata properties we are using required reading the entire dataset that is being described. This is okay for small, local files, but can become a problem for large, remote files. This PR updates or removes those properties so that describing a dataset remains quick.
**Properties changing:**
- `hash` -> `uid`: Instead of hashing a file to create a unique identifier, we now hash some properties of the file. I renamed to `uid` so that we do not mislead users into thinking this is a hash of the entire file.
- `rows` & `fields`: simply counting the number of rows in a table could be a problem, so this is no longer part of the metadata. Number of fields also seems unnecessary; all fields are still listed under the `schema`.
- `n_features`: a new property for vectors, instead of `rows`. …

better handle remote files by avoiding full reads

---

README.md
requirements.txt
src/geometamaker/__init__.py
src/geometamaker/config.py
src/geometamaker/geometamaker.py
src/geometamaker/models.py
tests/test_geometamaker.py

This feature allows setting values for some metadata fields through the use of a "profile". Users might want to always use the same values for things like contact and license info. So a "profile" is a way to pass those values when describing a resource, without having to make separate calls to the resource's setters.
This PR also introduces a user-level config file that can be used to save a profile and re-use it by default. Values from this default profile will always be used when describing resources, unless they are overridden by a profile passed to `describe`.
Close #33

Feature: metadata profiles and user-configuration

---

src/geometamaker/geometamaker.py
src/geometamaker/models.py
tests/test_geometamaker.py

This feature uses `fsspec` to list the contents of a zip file without extracting it. `fsspec` is used in order for this feature to work the same on local and remote (`http`) files.
Fixes #40 
It's worth noting that we have #26 for adding support for other formats. `fsspec` supports these:
```python
fsspec.available_compressions()
[None, 'zip', 'bz2', 'gzip', 'lzma', 'xz']
```

Feature: list zipfile contents

---

requirements.txt
src/geometamaker/config.py
src/geometamaker/geometamaker.py
src/geometamaker/models.py
tests/test_geometamaker.py

- The last PR that included `gdal.UseExceptions` needed to also require we use a version of pygeoprocessing that does the same, so that exceptions there are handled properly, such as in `get_gis_type`
- There was also a bug in the "units" representation of the CRS, which is fixed here.
- Another bug in the `Config` test mocking is fixed (see Slack thread for explanation)
- Fixes #50

Bump Pygeoprocessing requirement, and a couple other fixes

---

src/geometamaker/geometamaker.py
src/geometamaker/models.py
src/geometamaker/utils.py
tests/test_geometamaker.py

Instead of dumping a string with newline characters directly, we can add a yaml block indicator ( `|` ) to indicate that the dumper should treat newline chars as newlines. https://yaml-multiline.info/
The upshot is that we get this "literal" block,
```yaml
lineage: |-
Created by natcap.invest.annual_water_yield.execute(
{'biophysical_table_path': 'C:\\Users\\dmf\\projects\\invest\\data\\invest-sample-data\\Annual_Water_Yield\\biophysical_table_gura.csv',
'depth_to_root_rest_layer_path': 'C:\\Users\\dmf\\projects\\invest\\data\\invest-sample-data\\Annual_Water_Yield\\depth_to_root_restricting_layer_gura.tif',
'eto_path': 'C:\\Users\\dmf\\projects\\invest\\data\\invest-sample-data\\Annual_Water_Yield\\reference_ET_gura.tif',
'lulc_path': …
```

Feature: respect newline characters in strings

---

src/geometamaker/models.py
tests/test_geometamaker.py

This is patterned exactly the same as the `keywords` attribute.
Fixes #47

add set and get methods for placenames.

---

.github/workflows/test.yml
pyproject.toml
requirements.txt
src/geometamaker/config.py
src/geometamaker/geometamaker.py
src/geometamaker/models.py
tests/test_geometamaker.py

This PR refactors the data models to inherit from Pydantic's `BaseModel`.
Pydantic is useful for type-checking (aka "validation"). And using `BaseModel` instead of `pydantic.dataclasses` neatly works around the problem described in #54 
We're now validating metadata documents on `Resource.__init__`, in other words, when a new dataset is described or an existing document is loaded from a file. And we also validate fields on assignment.
One change to the metadata specification:
`schema` is a reserved attribute by Pydantic. So I renamed our `schema` attribute to `data_model`, and added a clause to do that migration when an existing yaml doc is loaded, if needed. We should do some future planning around metadata schema versioning.
Fixes #54 
Fixes #29

Refactor to take advantage of Pydantic validation

---

README.md
pyproject.toml
requirements.txt
src/geometamaker/__init__.py
src/geometamaker/cli.py
src/geometamaker/config.py
src/geometamaker/geometamaker.py
src/geometamaker/models.py
tests/test_geometamaker.py

This PR adds a command-line interface.
I also added `geometamaker.describe_dir` and `geometamaker.validate_dir` to more easily process a batch of files in a directory tree.
Fixes #43 
```
λ geometamaker --help
Usage: geometamaker [OPTIONS] COMMAND [ARGS]...
Options:
-v         Override the default verbosity of logging. Use "-vvv" for debug-
level logging. Omit this flag for default, info-level logging.
--version  Show the version and exit.
--help     Show this message and exit.
Commands:
config    Configure GeoMetaMaker with information to apply to all metadata
descriptions
describe  Generate metadata for geospatial or tabular data, or zip archives.
validate  Validate metadata documents for syntax or type errors.
```
```
λ geometamaker describe --help
Usage: geometamaker describe …
```

Feature: Command-line interface

---

src/geometamaker/geometamaker.py
src/geometamaker/models.py
src/geometamaker/utils.py

Based on feedback, we have a few changes to attributes:
`mediatype`: removed, not useful
`name`: removed, not useful, redundant with `path` and too easily confused with `title`
`raster_size`: changed from `list` to `dict` to allow "width" and "height" labels
`metadata_version`: changed to `geometamaker_version` to be more accurate
All these changes are made backwards-compatible with respect to `describing` a dataset with an existing `yml` document.  When a pre-existing document is loaded, incompatible attributes are removed/replaced with warnings issued.
`validate` will issue `ValidationErrors` on a document with the old attributes.
Fixes #58

Minor updates to data models

---

.github/workflows/test.yml
HISTORY.rst
pyproject.toml
requirements.txt
src/geometamaker/cli.py
src/geometamaker/models.py
tests/test_geometamaker.py

Various small bugfixes. 
Fixes #71 - always write utf-8 documents
Fixes #65 - fix validation message formatting for attributes nested in a list
Fixes #64 - minimum version requirements for pydantic and frictionless
Fixes #46 - test against python 3.13
Fixes #70 - don't fail on rasters that have no nodata value.

Various bugfixes

---

HISTORY.rst
src/geometamaker/geometamaker.py
tests/test_geometamaker.py

Avoid a runtime error if we encounter an unreadable yaml file while validating a directory. If a user wants to validate a specific file -- not a whole directory -- then I think it's best to not handle the exception.
Fixes #62

added exception handling to `validate_dir`

---

pyproject.toml

I overlooked the need to list dependencies anywhere besides `requirements.txt`. But then I realized that a simple `pip install` was not installing any dependencies. 
The feature I used here is listed as "BETA" in the docs, but it works -- `pip install` discovers and installs missing dependencies. This project is not using `setup.py`. Please let me know if you know of a better approach. Thanks!
https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#dynamic-metadata

include dependencies from file in pyproject.toml

---

HISTORY.rst
src/geometamaker/cli.py
tests/test_geometamaker.py

`geometamaker.describe` is already setup to handle reading from remote sources, but CLI validation was preventing that for `geometamaker describe`. I updated the argument validation to handle a URL or a local filepath.
Fixes #78

allow CLI to describe remote datasets.

---

README.md
docs/environment-rtd.yml
docs/source/archive_resource.rst
docs/source/basic_usage.rst
docs/source/conf.py
docs/source/index.rst
docs/source/installation.rst
docs/source/metadata_resources.rst
docs/source/profile.rst
docs/source/raster_resource.rst
docs/source/table_resource.rst
docs/source/vector_resource.rst
src/geometamaker/models.py
tests/test_geometamaker.py

This PR improves API documentation. API docs now include,
* A Basic Usage page currently based on content in the readme
* Pages for each of the main user-facing data models, which now include docstrings for attributes
* Better-formatted docs for Pydantic classes.
Fixes #67

Updated API docs; including docstrings for model attributes

---

HISTORY.rst
src/geometamaker/geometamaker.py
src/geometamaker/models.py
tests/test_geometamaker.py

This feature allows a user to `describe` `.tar` and `.tgz` (and `.tar.gz`) archives (essentially, list the contents of the archive) without extracting them. This PR is similar to PR #42.
Note that this feature does _not_ address use-case 1 in #26, i.e. create
> metadata for single files that happen to be zips, tgz, etc
Fixes #26

Add support for tar gzip files

---

HISTORY.rst
README.md
docs/source/collection_resource.rst
docs/source/metadata_resources.rst
src/geometamaker/__init__.py
src/geometamaker/cli.py
src/geometamaker/geometamaker.py
src/geometamaker/models.py
tests/test_geometamaker.py

Users can now create metadata for collections, i.e., folders. Collection-level metadata includes a list of the files contained within the directory, along with their `description`s and `metadata` (or placeholders if none). Users can specify `depth` to determine how many subdirectories to traverse when identifying files in the collection. It is also possible to provide a regular expression to exclude certain files from collection metadata. Hidden files are excluded by default.
Note that Collections are described slightly differently than other resources:
- collection metadata are located in a sibling directory and are tagged with `-metadata` (i.e., the metadata for /path/to/collection will be /path/to/collection-metadata.yml
- users cannot call `describe` on collections
`describe_dir` has …

Feature: create metadata for collections/directories
